// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Identity interface {
	IsIdentity()
}

type Asset struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Assignment struct {
	Identity   Identity   `json:"identity"`
	Permission Permission `json:"permission"`
	Asset      *Asset     `json:"asset"`
}

type Group struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Users  []*User  `json:"users,omitempty"`
	Assets []*Asset `json:"assets,omitempty"`
}

func (Group) IsIdentity() {}

type Mutation struct {
}

type Query struct {
}

type Tag struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Assets []*Asset `json:"assets"`
}

type User struct {
	ID     string   `json:"id"`
	Email  string   `json:"email"`
	Groups []*Group `json:"groups,omitempty"`
	Assets []*Asset `json:"assets,omitempty"`
}

func (User) IsIdentity() {}

type Permission string

const (
	PermissionRead  Permission = "READ"
	PermissionWrite Permission = "WRITE"
)

var AllPermission = []Permission{
	PermissionRead,
	PermissionWrite,
}

func (e Permission) IsValid() bool {
	switch e {
	case PermissionRead, PermissionWrite:
		return true
	}
	return false
}

func (e Permission) String() string {
	return string(e)
}

func (e *Permission) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Permission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Permission", str)
	}
	return nil
}

func (e Permission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PermissionQuery string

const (
	PermissionQueryRead  PermissionQuery = "READ"
	PermissionQueryWrite PermissionQuery = "WRITE"
	PermissionQueryAll   PermissionQuery = "ALL"
)

var AllPermissionQuery = []PermissionQuery{
	PermissionQueryRead,
	PermissionQueryWrite,
	PermissionQueryAll,
}

func (e PermissionQuery) IsValid() bool {
	switch e {
	case PermissionQueryRead, PermissionQueryWrite, PermissionQueryAll:
		return true
	}
	return false
}

func (e PermissionQuery) String() string {
	return string(e)
}

func (e *PermissionQuery) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PermissionQuery(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PermissionQuery", str)
	}
	return nil
}

func (e PermissionQuery) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
